version: 9.9.{build}
clone_depth: 3
configuration: Release
skip_branch_with_pr: true
environment:
  STORE_PASSWORD:
    secure: ZF3GiQxQ98B1HGKZOwlnmris5yN68mvx3UF6TVsnpws=
  PASSWORD:
    secure: mqbXr4+cn3l9YNyKhOezbA==
  matrix:
    - PRODUCT: ios
      APPVEYOR_BUILD_WORKER_IMAGE: macOS-bigsur
      TMS_USER: israelhikingmap@gmail.com
      TMS_APPLE_APPLICATION_SPECIFIC_PASSWORD:
        secure: oSccSp70X/744XBpfRV4UVJZKxN1jMYHxn3OHFsTSVE=
    
for:
  -
    matrix:
      only:
        - PRODUCT: docker
    build_script:
    - pwsh: >-
        $BuildAndPublishDocker = "$env:APPVEYOR_BUILD_FOLDER\Scripts\BuildAndPublishDocker.ps1"

        & "$BuildAndPublishDocker"

  -
    matrix:
      only: 
        - PRODUCT: tests
    install:
      - sh: nvm install 14.17
    before_build:
      - pwsh: dotnet restore
    build:
      project: IsraelHiking.sln
      parallel: true
      verbosity: minimal
    test: off
    after_build:
      - pwsh: >-
            $RunTests = "$env:APPVEYOR_BUILD_FOLDER\Scripts\RunTests.ps1"

            & "$RunTests"

  -
    matrix:
      only:
        - PRODUCT: android
    install:
      - ps: Install-Product node LTS    
    build_script:
    - pwsh: >-
        $BuildAndPublishAndroid = "$env:APPVEYOR_BUILD_FOLDER\Scripts\BuildAndPublishAndroid.ps1"

        & "$BuildAndPublishAndroid"

  -
    matrix:
      only:
        - PRODUCT: ios
      fast_finish: true
    install:
      #- sh: sudo xcode-select -s /Applications/Xcode.app/Contents/Developer
      - sh: nvm install 14.17
    build_script: 
    - pwsh: >-
        $BuildAndPublishIOS = "$env:APPVEYOR_BUILD_FOLDER\Scripts\BuildAndPublishIOS.ps1"

        & "$BuildAndPublishIOS"
        
deploy:
- provider: GitHub
  auth_token:
    secure: sf1+2Hyi+fcURBUGv5B0GMgXoqR4Ib9wKW7JQAMeuUP0Z9DxOoV24Q2kzV4jmLPn
  repository: IsraelHikingMap/Site
  draft: true
  on:
    APPVEYOR_REPO_TAG: true
